/// <reference types="vite/client" />
// @vitest-environment edge-runtime
import {convexTest} from 'convex-test';import {afterEach,expect,test,vi} from 'vitest';import {api,internal} from './_generated/api';import schema from './schema';import {encryptSecret} from './lib/crypto';
const modules=import.meta.glob('./**/*.ts');afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();vi.useRealTimers();});
async function setup(){vi.stubEnv('ENCRYPTION_KEY','ab'.repeat(32));const t=convexTest(schema,modules);const ids=await t.run(async ctx=>{const userId=await ctx.db.insert('users',{clerkUserId:'owner'});const orgId=await ctx.db.insert('orgs',{name:'A',slug:'a',ownerId:userId});const workspaceId=await ctx.db.insert('workspaces',{orgId,name:'A',isDefault:true});const membershipId=await ctx.db.insert('memberships',{orgId,userId,role:'owner'});const id=await ctx.db.insert('companyWhatsappConnections',{workspaceId,createdBy:userId,status:'active',sessionId:'own-session',phoneNumber:'+31600000001',encryptedApiKey:await encryptSecret('own-key'),encryptedWebhookSecret:await encryptSecret('secret'),verifiedAt:1});return {id,workspaceId,membershipId};});const fetchMock=vi.fn(async()=>Response.json({success:true,data:{sessionId:'own-session',status:'WORKING',isConnected:true,phoneNumber:'+31600000001'}}));vi.stubGlobal('fetch',fetchMock);return {t,...ids,fetchMock,caller:t.withIdentity({subject:'owner'})};}
test.each(['offline','wrong-phone','wrong-session','provider-error','connected'])('health check handles %s with own credentials',async kind=>{const {t,id,caller,fetchMock,workspaceId}=await setup();fetchMock.mockResolvedValue(kind==='provider-error'?new Response('',{status:500}):Response.json({success:true,data:{sessionId:kind==='wrong-session'?'foreign':'own-session',phoneNumber:kind==='wrong-phone'?'+31699999999':'+31600000001',status:kind==='offline'?'STOPPED':'WORKING',isConnected:kind!=='offline'}}));await caller.action(api.companyWhatsappHealth.checkNow,{id});const r=await t.run(ctx=>ctx.db.get(id));expect(r?.health).toBe(kind==='connected'?'connected':kind==='provider-error'||kind==='wrong-session'?'unknown':'disconnected');if(kind!=='connected')await expect(t.query(internal.companyWhatsapp.transport,{workspaceId})).rejects.toThrow('niet bevestigd');else expect(await t.query(internal.companyWhatsapp.transport,{workspaceId})).toMatchObject({apiKey:'own-key'});});
test('anonymous cannot probe; paused connections cause no provider requests',async()=>{const {t,id,caller,fetchMock}=await setup();await expect(t.action(api.companyWhatsappHealth.checkNow,{id})).rejects.toThrow();expect(fetchMock).not.toHaveBeenCalled();await caller.mutation(api.companyWhatsapp.disable,{id});await t.action(internal.companyWhatsappHealth.probe,{id});expect(fetchMock).not.toHaveBeenCalled();});
test('stale results and pause during an in-flight check cannot restore a connection',async()=>{const {t,id,caller,fetchMock}=await setup();await t.mutation(internal.companyWhatsappHealth.save,{id,manual:false,checkedAt:200,health:'disconnected',reason:'offline'});await t.mutation(internal.companyWhatsappHealth.save,{id,manual:false,checkedAt:100,health:'connected',reason:'old'});expect((await t.run(ctx=>ctx.db.get(id)))?.health).toBe('disconnected');const fn=fetchMock.getMockImplementation()!;fetchMock.mockImplementation(async()=>{await caller.mutation(api.companyWhatsapp.disable,{id});return fn();});await caller.action(api.companyWhatsappHealth.checkNow,{id});expect(await t.run(ctx=>ctx.db.get(id))).toMatchObject({status:'disabled',health:'disconnected'});});
test('scheduled sweep checks active connections and restores recovered transport',async()=>{const {t,id,workspaceId,fetchMock}=await setup();await t.run(ctx=>ctx.db.patch(id,{health:'unknown'}));vi.useFakeTimers();await t.action(internal.companyWhatsappHealth.sweep,{});await t.finishAllScheduledFunctions(vi.runAllTimers);expect(fetchMock).toHaveBeenCalledTimes(1);expect(await t.query(internal.companyWhatsapp.transport,{workspaceId})).toMatchObject({connectionId:id});});
