import {useState} from 'react'
import {createFileRoute,Link} from '@tanstack/react-router'
import {useMutation,useQuery} from 'convex/react'
import {api} from '../../convex/_generated/api'
import {Button} from '#/components/ui/button'
import {Card,CardContent} from '#/components/ui/card'
export const Route=createFileRoute('/crm/settings_/team')({component:Page})
function Page(){
 const tenants=useQuery(api.userProfiles.myTenants),workspaceId=tenants?.find(t=>t.workspace)?.workspace?.id,profile=useQuery(api.userProfiles.me)
 const team=useQuery(api.companyOnboarding.team,workspaceId?{workspaceId}:'skip')
 const invite=useMutation(api.companyOnboarding.invite),revoke=useMutation(api.companyOnboarding.revoke),remove=useMutation(api.companyOnboarding.removeMember)
 const [email,setEmail]=useState(''),[role,setRole]=useState<'member'|'admin'>('member'),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Bewerking mislukt')}finally{setBusy(false)}}
 const ownMembership=tenants?.find(t=>t.workspace?.id===workspaceId)?.membershipId
 return <div className="mx-auto max-w-3xl space-y-5"><Link to="/crm/settings">← Instellingen</Link><h1 className="text-2xl font-bold">Bedrijf en team</h1><Link className="text-violet-700 underline" to="/aan-de-slag">Startoverzicht en inrichting</Link><p>Medewerkers werken in het CRM. Bedrijfsbeheerders beheren ook instellingen, campagnes en aankopen. Alleen de eigenaar kan beheerders uitnodigen of verwijderen. Rollen gelden voor het hele bedrijf.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
 {!team?<p>Team laden…</p>:<><Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold">{team.company}</h2>{team.members.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2"><div>{m.name||m.email||'Teamlid'}<span className="block text-sm text-zinc-600">{m.email} · {m.role==='owner'?'Eigenaar':m.role==='admin'?'Bedrijfsbeheerder':'Medewerker'}</span></div>{m.id!==ownMembership && m.role!=='owner' && (m.role==='member'||team.canInviteAdmins)&&<Button variant="outline" disabled={busy||!profile} onClick={()=>{if(window.confirm('Toegang tot dit bedrijf intrekken? CRM-gegevens blijven bewaard.'))run(()=>remove({id:m.id}))}}>Toegang intrekken</Button>}</div>)}</CardContent></Card>
 <Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold">Teamlid uitnodigen</h2><form className="space-y-3" onSubmit={e=>{e.preventDefault();run(async()=>{if(!workspaceId)return;const r=await invite({workspaceId,email,role});setCode(r.code)})}}><label className="grid gap-1">E-mailadres ontvanger<input type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} className="rounded border p-2"/></label><label className="grid gap-1">Rol<select value={role} onChange={e=>setRole(e.target.value as 'member'|'admin')} className="rounded border p-2"><option value="member">Medewerker</option>{team.canInviteAdmins&&<option value="admin">Bedrijfsbeheerder</option>}</select></label><Button disabled={busy}>Uitnodigingscode maken</Button></form><p className="text-sm">Er wordt geen e-mail verstuurd. Deel de code zelf met de ontvanger. De code is zeven dagen geldig en kan eenmaal worden gebruikt. Een nieuwe code voor hetzelfde adres vervangt de vorige.</p>
 {code&&<div className="space-y-2 rounded border p-3"><label className="grid gap-1">Eenmalig getoonde code<input readOnly value={code} onFocus={e=>e.target.select()} className="rounded border p-2 font-mono text-xs"/></label><p className="text-sm">Laat de ontvanger inloggen met het uitgenodigde e-mailadres en deze code invullen bij <Link to="/aan-de-slag" className="underline">Aan de slag → Ik heb een uitnodiging</Link>.</p><Button variant="outline" onClick={()=>setCode('')}>Code verbergen</Button></div>}
 <h3 className="font-semibold">Open uitnodigingen</h3>{!team.invites.length?<p className="text-sm">Geen open uitnodigingen.</p>:team.invites.map(i=><div key={i.id} className="flex flex-wrap justify-between gap-2 border-t py-2"><p>{i.email} · {i.role==='admin'?'Bedrijfsbeheerder':'Medewerker'}<span className="block text-xs">Geldig tot {new Date(i.expiresAt).toLocaleString('nl-NL')}</span></p>{(i.role==='member'||team.canInviteAdmins)&&<Button variant="outline" disabled={busy} onClick={()=>run(()=>revoke({id:i.id}))}>Intrekken</Button>}</div>)}</CardContent></Card></>}
 <Link to="/crm/settings/handleiding" className="text-violet-700 underline">Handleiding voor bedrijven</Link></div>
}
