/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmWorkflowsRouteImport } from './routes/crm.workflows'
import { Route as CrmPipelinesRouteImport } from './routes/crm.pipelines'
import { Route as CrmMessagesRouteImport } from './routes/crm.messages'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmContactsIdRouteImport } from './routes/crm.contacts_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWorkflowsRoute = CrmWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelinesRoute = CrmPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMessagesRoute = CrmMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIdRoute = CrmContactsIdRouteImport.update({
  id: '/contacts_/$id',
  path: '/contacts/$id',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm': typeof CrmIndexRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/contacts_/$id': typeof CrmContactsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/workflows'
    | '/crm/'
    | '/crm/contacts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/workflows'
    | '/crm'
    | '/crm/contacts/$id'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/workflows'
    | '/crm/'
    | '/crm/contacts_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/workflows': {
      id: '/crm/workflows'
      path: '/workflows'
      fullPath: '/crm/workflows'
      preLoaderRoute: typeof CrmWorkflowsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipelines': {
      id: '/crm/pipelines'
      path: '/pipelines'
      fullPath: '/crm/pipelines'
      preLoaderRoute: typeof CrmPipelinesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/messages': {
      id: '/crm/messages'
      path: '/messages'
      fullPath: '/crm/messages'
      preLoaderRoute: typeof CrmMessagesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts_/$id': {
      id: '/crm/contacts_/$id'
      path: '/contacts/$id'
      fullPath: '/crm/contacts/$id'
      preLoaderRoute: typeof CrmContactsIdRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface CrmRouteChildren {
  CrmContactsRoute: typeof CrmContactsRoute
  CrmMessagesRoute: typeof CrmMessagesRoute
  CrmPipelinesRoute: typeof CrmPipelinesRoute
  CrmWorkflowsRoute: typeof CrmWorkflowsRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmContactsIdRoute: typeof CrmContactsIdRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmContactsRoute: CrmContactsRoute,
  CrmMessagesRoute: CrmMessagesRoute,
  CrmPipelinesRoute: CrmPipelinesRoute,
  CrmWorkflowsRoute: CrmWorkflowsRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmContactsIdRoute: CrmContactsIdRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
