/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmWorkflowsRouteImport } from './routes/crm.workflows'
import { Route as CrmSettingsRouteImport } from './routes/crm.settings'
import { Route as CrmPipelinesRouteImport } from './routes/crm.pipelines'
import { Route as CrmMessagesRouteImport } from './routes/crm.messages'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmWorkflowsIdRouteImport } from './routes/crm.workflows_.$id'
import { Route as CrmSettingsWhatsappRouteImport } from './routes/crm.settings_.whatsapp'
import { Route as CrmSettingsTemplatesRouteImport } from './routes/crm.settings_.templates'
import { Route as CrmSettingsPipelineRouteImport } from './routes/crm.settings_.pipeline'
import { Route as CrmSettingsMetaRouteImport } from './routes/crm.settings_.meta'
import { Route as CrmSettingsLeadFlowRouteImport } from './routes/crm.settings_.lead-flow'
import { Route as CrmSettingsAiAgentRouteImport } from './routes/crm.settings_.ai-agent'
import { Route as CrmContactsImportRouteImport } from './routes/crm.contacts_.import'
import { Route as CrmContactsIdRouteImport } from './routes/crm.contacts_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWorkflowsRoute = CrmWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelinesRoute = CrmPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMessagesRoute = CrmMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWorkflowsIdRoute = CrmWorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsWhatsappRoute = CrmSettingsWhatsappRouteImport.update({
  id: '/settings_/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsTemplatesRoute = CrmSettingsTemplatesRouteImport.update({
  id: '/settings_/templates',
  path: '/settings/templates',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsPipelineRoute = CrmSettingsPipelineRouteImport.update({
  id: '/settings_/pipeline',
  path: '/settings/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsMetaRoute = CrmSettingsMetaRouteImport.update({
  id: '/settings_/meta',
  path: '/settings/meta',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsLeadFlowRoute = CrmSettingsLeadFlowRouteImport.update({
  id: '/settings_/lead-flow',
  path: '/settings/lead-flow',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsAiAgentRoute = CrmSettingsAiAgentRouteImport.update({
  id: '/settings_/ai-agent',
  path: '/settings/ai-agent',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsImportRoute = CrmContactsImportRouteImport.update({
  id: '/contacts_/import',
  path: '/contacts/import',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIdRoute = CrmContactsIdRouteImport.update({
  id: '/contacts_/$id',
  path: '/contacts/$id',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/contacts/import': typeof CrmContactsImportRoute
  '/crm/settings/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings/meta': typeof CrmSettingsMetaRoute
  '/crm/settings/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows/$id': typeof CrmWorkflowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm': typeof CrmIndexRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/contacts/import': typeof CrmContactsImportRoute
  '/crm/settings/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings/meta': typeof CrmSettingsMetaRoute
  '/crm/settings/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows/$id': typeof CrmWorkflowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/contacts_/$id': typeof CrmContactsIdRoute
  '/crm/contacts_/import': typeof CrmContactsImportRoute
  '/crm/settings_/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings_/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings_/meta': typeof CrmSettingsMetaRoute
  '/crm/settings_/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings_/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings_/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows_/$id': typeof CrmWorkflowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/workflows'
    | '/crm/'
    | '/crm/contacts/$id'
    | '/crm/contacts/import'
    | '/crm/settings/ai-agent'
    | '/crm/settings/lead-flow'
    | '/crm/settings/meta'
    | '/crm/settings/pipeline'
    | '/crm/settings/templates'
    | '/crm/settings/whatsapp'
    | '/crm/workflows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/workflows'
    | '/crm'
    | '/crm/contacts/$id'
    | '/crm/contacts/import'
    | '/crm/settings/ai-agent'
    | '/crm/settings/lead-flow'
    | '/crm/settings/meta'
    | '/crm/settings/pipeline'
    | '/crm/settings/templates'
    | '/crm/settings/whatsapp'
    | '/crm/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/login'
    | '/crm/contacts'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/workflows'
    | '/crm/'
    | '/crm/contacts_/$id'
    | '/crm/contacts_/import'
    | '/crm/settings_/ai-agent'
    | '/crm/settings_/lead-flow'
    | '/crm/settings_/meta'
    | '/crm/settings_/pipeline'
    | '/crm/settings_/templates'
    | '/crm/settings_/whatsapp'
    | '/crm/workflows_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/workflows': {
      id: '/crm/workflows'
      path: '/workflows'
      fullPath: '/crm/workflows'
      preLoaderRoute: typeof CrmWorkflowsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipelines': {
      id: '/crm/pipelines'
      path: '/pipelines'
      fullPath: '/crm/pipelines'
      preLoaderRoute: typeof CrmPipelinesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/messages': {
      id: '/crm/messages'
      path: '/messages'
      fullPath: '/crm/messages'
      preLoaderRoute: typeof CrmMessagesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/workflows_/$id': {
      id: '/crm/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/crm/workflows/$id'
      preLoaderRoute: typeof CrmWorkflowsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/whatsapp': {
      id: '/crm/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/crm/settings/whatsapp'
      preLoaderRoute: typeof CrmSettingsWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/templates': {
      id: '/crm/settings_/templates'
      path: '/settings/templates'
      fullPath: '/crm/settings/templates'
      preLoaderRoute: typeof CrmSettingsTemplatesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/pipeline': {
      id: '/crm/settings_/pipeline'
      path: '/settings/pipeline'
      fullPath: '/crm/settings/pipeline'
      preLoaderRoute: typeof CrmSettingsPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/meta': {
      id: '/crm/settings_/meta'
      path: '/settings/meta'
      fullPath: '/crm/settings/meta'
      preLoaderRoute: typeof CrmSettingsMetaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/lead-flow': {
      id: '/crm/settings_/lead-flow'
      path: '/settings/lead-flow'
      fullPath: '/crm/settings/lead-flow'
      preLoaderRoute: typeof CrmSettingsLeadFlowRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/ai-agent': {
      id: '/crm/settings_/ai-agent'
      path: '/settings/ai-agent'
      fullPath: '/crm/settings/ai-agent'
      preLoaderRoute: typeof CrmSettingsAiAgentRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts_/import': {
      id: '/crm/contacts_/import'
      path: '/contacts/import'
      fullPath: '/crm/contacts/import'
      preLoaderRoute: typeof CrmContactsImportRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts_/$id': {
      id: '/crm/contacts_/$id'
      path: '/contacts/$id'
      fullPath: '/crm/contacts/$id'
      preLoaderRoute: typeof CrmContactsIdRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface CrmRouteChildren {
  CrmContactsRoute: typeof CrmContactsRoute
  CrmMessagesRoute: typeof CrmMessagesRoute
  CrmPipelinesRoute: typeof CrmPipelinesRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
  CrmWorkflowsRoute: typeof CrmWorkflowsRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmContactsIdRoute: typeof CrmContactsIdRoute
  CrmContactsImportRoute: typeof CrmContactsImportRoute
  CrmSettingsAiAgentRoute: typeof CrmSettingsAiAgentRoute
  CrmSettingsLeadFlowRoute: typeof CrmSettingsLeadFlowRoute
  CrmSettingsMetaRoute: typeof CrmSettingsMetaRoute
  CrmSettingsPipelineRoute: typeof CrmSettingsPipelineRoute
  CrmSettingsTemplatesRoute: typeof CrmSettingsTemplatesRoute
  CrmSettingsWhatsappRoute: typeof CrmSettingsWhatsappRoute
  CrmWorkflowsIdRoute: typeof CrmWorkflowsIdRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmContactsRoute: CrmContactsRoute,
  CrmMessagesRoute: CrmMessagesRoute,
  CrmPipelinesRoute: CrmPipelinesRoute,
  CrmSettingsRoute: CrmSettingsRoute,
  CrmWorkflowsRoute: CrmWorkflowsRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmContactsIdRoute: CrmContactsIdRoute,
  CrmContactsImportRoute: CrmContactsImportRoute,
  CrmSettingsAiAgentRoute: CrmSettingsAiAgentRoute,
  CrmSettingsLeadFlowRoute: CrmSettingsLeadFlowRoute,
  CrmSettingsMetaRoute: CrmSettingsMetaRoute,
  CrmSettingsPipelineRoute: CrmSettingsPipelineRoute,
  CrmSettingsTemplatesRoute: CrmSettingsTemplatesRoute,
  CrmSettingsWhatsappRoute: CrmSettingsWhatsappRoute,
  CrmWorkflowsIdRoute: CrmWorkflowsIdRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
