/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanDeSlagRouteImport } from './routes/aan-de-slag'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrerenRouteImport } from './routes/registreren'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmAppsRouteImport } from './routes/crm.apps'
import { Route as CrmCampaignsRouteImport } from './routes/crm.campaigns'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmLeadgenRouteImport } from './routes/crm.leadgen'
import { Route as CrmMessagesRouteImport } from './routes/crm.messages'
import { Route as CrmPipelinesRouteImport } from './routes/crm.pipelines'
import { Route as CrmSettingsRouteImport } from './routes/crm.settings'
import { Route as CrmTakenRouteImport } from './routes/crm.taken'
import { Route as CrmWebhookSignalenRouteImport } from './routes/crm.webhook-signalen'
import { Route as CrmWorkflowsRouteImport } from './routes/crm.workflows'
import { Route as FeedIndexRouteImport } from './routes/feed.index'
import { Route as FeedPurchasedRouteImport } from './routes/feed.purchased'
import { Route as FeedSettingsRouteImport } from './routes/feed.settings'
import { Route as FeedSoldRouteImport } from './routes/feed.sold'
import { Route as FeedWalletRouteImport } from './routes/feed.wallet'
import { Route as FeedOnboardingRouteImport } from './routes/feed_.onboarding'
import { Route as CrmCampaignsIdRouteImport } from './routes/crm.campaigns_.$id'
import { Route as CrmContactsIdRouteImport } from './routes/crm.contacts_.$id'
import { Route as CrmContactsImportRouteImport } from './routes/crm.contacts_.import'
import { Route as CrmSettingsAiAgentRouteImport } from './routes/crm.settings_.ai-agent'
import { Route as CrmSettingsCustomFieldsRouteImport } from './routes/crm.settings_.custom-fields'
import { Route as CrmSettingsEigenWhatsappRouteImport } from './routes/crm.settings_.eigen-whatsapp'
import { Route as CrmSettingsEmailRouteImport } from './routes/crm.settings_.email'
import { Route as CrmSettingsHandleidingRouteImport } from './routes/crm.settings_.handleiding'
import { Route as CrmSettingsLeadFlowRouteImport } from './routes/crm.settings_.lead-flow'
import { Route as CrmSettingsMetaRouteImport } from './routes/crm.settings_.meta'
import { Route as CrmSettingsPipelineRouteImport } from './routes/crm.settings_.pipeline'
import { Route as CrmSettingsSmsRouteImport } from './routes/crm.settings_.sms'
import { Route as CrmSettingsTeamRouteImport } from './routes/crm.settings_.team'
import { Route as CrmSettingsTemplatesRouteImport } from './routes/crm.settings_.templates'
import { Route as CrmSettingsWhatsappRouteImport } from './routes/crm.settings_.whatsapp'
import { Route as CrmWorkflowsIdRouteImport } from './routes/crm.workflows_.$id'
import { Route as FeedLeadIdRouteImport } from './routes/feed.lead_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanDeSlagRoute = AanDeSlagRouteImport.update({
  id: '/aan-de-slag',
  path: '/aan-de-slag',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenRoute = RegistrerenRouteImport.update({
  id: '/registreren',
  path: '/registreren',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAppsRoute = CrmAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCampaignsRoute = CrmCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadgenRoute = CrmLeadgenRouteImport.update({
  id: '/leadgen',
  path: '/leadgen',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMessagesRoute = CrmMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelinesRoute = CrmPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTakenRoute = CrmTakenRouteImport.update({
  id: '/taken',
  path: '/taken',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWebhookSignalenRoute = CrmWebhookSignalenRouteImport.update({
  id: '/webhook-signalen',
  path: '/webhook-signalen',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWorkflowsRoute = CrmWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => CrmRoute,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRoute,
} as any)
const FeedPurchasedRoute = FeedPurchasedRouteImport.update({
  id: '/purchased',
  path: '/purchased',
  getParentRoute: () => FeedRoute,
} as any)
const FeedSettingsRoute = FeedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FeedRoute,
} as any)
const FeedSoldRoute = FeedSoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => FeedRoute,
} as any)
const FeedWalletRoute = FeedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => FeedRoute,
} as any)
const FeedOnboardingRoute = FeedOnboardingRouteImport.update({
  id: '/feed_/onboarding',
  path: '/feed/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCampaignsIdRoute = CrmCampaignsIdRouteImport.update({
  id: '/campaigns_/$id',
  path: '/campaigns/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIdRoute = CrmContactsIdRouteImport.update({
  id: '/contacts_/$id',
  path: '/contacts/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsImportRoute = CrmContactsImportRouteImport.update({
  id: '/contacts_/import',
  path: '/contacts/import',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsAiAgentRoute = CrmSettingsAiAgentRouteImport.update({
  id: '/settings_/ai-agent',
  path: '/settings/ai-agent',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsCustomFieldsRoute = CrmSettingsCustomFieldsRouteImport.update({
  id: '/settings_/custom-fields',
  path: '/settings/custom-fields',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsEigenWhatsappRoute =
  CrmSettingsEigenWhatsappRouteImport.update({
    id: '/settings_/eigen-whatsapp',
    path: '/settings/eigen-whatsapp',
    getParentRoute: () => CrmRoute,
  } as any)
const CrmSettingsEmailRoute = CrmSettingsEmailRouteImport.update({
  id: '/settings_/email',
  path: '/settings/email',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsHandleidingRoute = CrmSettingsHandleidingRouteImport.update({
  id: '/settings_/handleiding',
  path: '/settings/handleiding',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsLeadFlowRoute = CrmSettingsLeadFlowRouteImport.update({
  id: '/settings_/lead-flow',
  path: '/settings/lead-flow',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsMetaRoute = CrmSettingsMetaRouteImport.update({
  id: '/settings_/meta',
  path: '/settings/meta',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsPipelineRoute = CrmSettingsPipelineRouteImport.update({
  id: '/settings_/pipeline',
  path: '/settings/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsSmsRoute = CrmSettingsSmsRouteImport.update({
  id: '/settings_/sms',
  path: '/settings/sms',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsTeamRoute = CrmSettingsTeamRouteImport.update({
  id: '/settings_/team',
  path: '/settings/team',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsTemplatesRoute = CrmSettingsTemplatesRouteImport.update({
  id: '/settings_/templates',
  path: '/settings/templates',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsWhatsappRoute = CrmSettingsWhatsappRouteImport.update({
  id: '/settings_/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWorkflowsIdRoute = CrmWorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => CrmRoute,
} as any)
const FeedLeadIdRoute = FeedLeadIdRouteImport.update({
  id: '/lead_/$id',
  path: '/lead/$id',
  getParentRoute: () => FeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aan-de-slag': typeof AanDeSlagRoute
  '/crm': typeof CrmRouteWithChildren
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/registreren': typeof RegistrerenRoute
  '/crm/apps': typeof CrmAppsRoute
  '/crm/campaigns': typeof CrmCampaignsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leadgen': typeof CrmLeadgenRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/taken': typeof CrmTakenRoute
  '/crm/webhook-signalen': typeof CrmWebhookSignalenRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/feed/purchased': typeof FeedPurchasedRoute
  '/feed/settings': typeof FeedSettingsRoute
  '/feed/sold': typeof FeedSoldRoute
  '/feed/wallet': typeof FeedWalletRoute
  '/feed/onboarding': typeof FeedOnboardingRoute
  '/crm/': typeof CrmIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/crm/campaigns/$id': typeof CrmCampaignsIdRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/contacts/import': typeof CrmContactsImportRoute
  '/crm/settings/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings/custom-fields': typeof CrmSettingsCustomFieldsRoute
  '/crm/settings/eigen-whatsapp': typeof CrmSettingsEigenWhatsappRoute
  '/crm/settings/email': typeof CrmSettingsEmailRoute
  '/crm/settings/handleiding': typeof CrmSettingsHandleidingRoute
  '/crm/settings/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings/meta': typeof CrmSettingsMetaRoute
  '/crm/settings/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings/sms': typeof CrmSettingsSmsRoute
  '/crm/settings/team': typeof CrmSettingsTeamRoute
  '/crm/settings/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows/$id': typeof CrmWorkflowsIdRoute
  '/feed/lead/$id': typeof FeedLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aan-de-slag': typeof AanDeSlagRoute
  '/login': typeof LoginRoute
  '/registreren': typeof RegistrerenRoute
  '/crm/apps': typeof CrmAppsRoute
  '/crm/campaigns': typeof CrmCampaignsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leadgen': typeof CrmLeadgenRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/taken': typeof CrmTakenRoute
  '/crm/webhook-signalen': typeof CrmWebhookSignalenRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/feed/purchased': typeof FeedPurchasedRoute
  '/feed/settings': typeof FeedSettingsRoute
  '/feed/sold': typeof FeedSoldRoute
  '/feed/wallet': typeof FeedWalletRoute
  '/feed/onboarding': typeof FeedOnboardingRoute
  '/crm': typeof CrmIndexRoute
  '/feed': typeof FeedIndexRoute
  '/crm/campaigns/$id': typeof CrmCampaignsIdRoute
  '/crm/contacts/$id': typeof CrmContactsIdRoute
  '/crm/contacts/import': typeof CrmContactsImportRoute
  '/crm/settings/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings/custom-fields': typeof CrmSettingsCustomFieldsRoute
  '/crm/settings/eigen-whatsapp': typeof CrmSettingsEigenWhatsappRoute
  '/crm/settings/email': typeof CrmSettingsEmailRoute
  '/crm/settings/handleiding': typeof CrmSettingsHandleidingRoute
  '/crm/settings/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings/meta': typeof CrmSettingsMetaRoute
  '/crm/settings/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings/sms': typeof CrmSettingsSmsRoute
  '/crm/settings/team': typeof CrmSettingsTeamRoute
  '/crm/settings/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows/$id': typeof CrmWorkflowsIdRoute
  '/feed/lead/$id': typeof FeedLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aan-de-slag': typeof AanDeSlagRoute
  '/crm': typeof CrmRouteWithChildren
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/registreren': typeof RegistrerenRoute
  '/crm/apps': typeof CrmAppsRoute
  '/crm/campaigns': typeof CrmCampaignsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leadgen': typeof CrmLeadgenRoute
  '/crm/messages': typeof CrmMessagesRoute
  '/crm/pipelines': typeof CrmPipelinesRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/taken': typeof CrmTakenRoute
  '/crm/webhook-signalen': typeof CrmWebhookSignalenRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/feed/purchased': typeof FeedPurchasedRoute
  '/feed/settings': typeof FeedSettingsRoute
  '/feed/sold': typeof FeedSoldRoute
  '/feed/wallet': typeof FeedWalletRoute
  '/feed_/onboarding': typeof FeedOnboardingRoute
  '/crm/': typeof CrmIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/crm/campaigns_/$id': typeof CrmCampaignsIdRoute
  '/crm/contacts_/$id': typeof CrmContactsIdRoute
  '/crm/contacts_/import': typeof CrmContactsImportRoute
  '/crm/settings_/ai-agent': typeof CrmSettingsAiAgentRoute
  '/crm/settings_/custom-fields': typeof CrmSettingsCustomFieldsRoute
  '/crm/settings_/eigen-whatsapp': typeof CrmSettingsEigenWhatsappRoute
  '/crm/settings_/email': typeof CrmSettingsEmailRoute
  '/crm/settings_/handleiding': typeof CrmSettingsHandleidingRoute
  '/crm/settings_/lead-flow': typeof CrmSettingsLeadFlowRoute
  '/crm/settings_/meta': typeof CrmSettingsMetaRoute
  '/crm/settings_/pipeline': typeof CrmSettingsPipelineRoute
  '/crm/settings_/sms': typeof CrmSettingsSmsRoute
  '/crm/settings_/team': typeof CrmSettingsTeamRoute
  '/crm/settings_/templates': typeof CrmSettingsTemplatesRoute
  '/crm/settings_/whatsapp': typeof CrmSettingsWhatsappRoute
  '/crm/workflows_/$id': typeof CrmWorkflowsIdRoute
  '/feed/lead_/$id': typeof FeedLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aan-de-slag'
    | '/crm'
    | '/feed'
    | '/login'
    | '/registreren'
    | '/crm/apps'
    | '/crm/campaigns'
    | '/crm/contacts'
    | '/crm/leadgen'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/taken'
    | '/crm/webhook-signalen'
    | '/crm/workflows'
    | '/feed/purchased'
    | '/feed/settings'
    | '/feed/sold'
    | '/feed/wallet'
    | '/feed/onboarding'
    | '/crm/'
    | '/feed/'
    | '/crm/campaigns/$id'
    | '/crm/contacts/$id'
    | '/crm/contacts/import'
    | '/crm/settings/ai-agent'
    | '/crm/settings/custom-fields'
    | '/crm/settings/eigen-whatsapp'
    | '/crm/settings/email'
    | '/crm/settings/handleiding'
    | '/crm/settings/lead-flow'
    | '/crm/settings/meta'
    | '/crm/settings/pipeline'
    | '/crm/settings/sms'
    | '/crm/settings/team'
    | '/crm/settings/templates'
    | '/crm/settings/whatsapp'
    | '/crm/workflows/$id'
    | '/feed/lead/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aan-de-slag'
    | '/login'
    | '/registreren'
    | '/crm/apps'
    | '/crm/campaigns'
    | '/crm/contacts'
    | '/crm/leadgen'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/taken'
    | '/crm/webhook-signalen'
    | '/crm/workflows'
    | '/feed/purchased'
    | '/feed/settings'
    | '/feed/sold'
    | '/feed/wallet'
    | '/feed/onboarding'
    | '/crm'
    | '/feed'
    | '/crm/campaigns/$id'
    | '/crm/contacts/$id'
    | '/crm/contacts/import'
    | '/crm/settings/ai-agent'
    | '/crm/settings/custom-fields'
    | '/crm/settings/eigen-whatsapp'
    | '/crm/settings/email'
    | '/crm/settings/handleiding'
    | '/crm/settings/lead-flow'
    | '/crm/settings/meta'
    | '/crm/settings/pipeline'
    | '/crm/settings/sms'
    | '/crm/settings/team'
    | '/crm/settings/templates'
    | '/crm/settings/whatsapp'
    | '/crm/workflows/$id'
    | '/feed/lead/$id'
  id:
    | '__root__'
    | '/'
    | '/aan-de-slag'
    | '/crm'
    | '/feed'
    | '/login'
    | '/registreren'
    | '/crm/apps'
    | '/crm/campaigns'
    | '/crm/contacts'
    | '/crm/leadgen'
    | '/crm/messages'
    | '/crm/pipelines'
    | '/crm/settings'
    | '/crm/taken'
    | '/crm/webhook-signalen'
    | '/crm/workflows'
    | '/feed/purchased'
    | '/feed/settings'
    | '/feed/sold'
    | '/feed/wallet'
    | '/feed_/onboarding'
    | '/crm/'
    | '/feed/'
    | '/crm/campaigns_/$id'
    | '/crm/contacts_/$id'
    | '/crm/contacts_/import'
    | '/crm/settings_/ai-agent'
    | '/crm/settings_/custom-fields'
    | '/crm/settings_/eigen-whatsapp'
    | '/crm/settings_/email'
    | '/crm/settings_/handleiding'
    | '/crm/settings_/lead-flow'
    | '/crm/settings_/meta'
    | '/crm/settings_/pipeline'
    | '/crm/settings_/sms'
    | '/crm/settings_/team'
    | '/crm/settings_/templates'
    | '/crm/settings_/whatsapp'
    | '/crm/workflows_/$id'
    | '/feed/lead_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanDeSlagRoute: typeof AanDeSlagRoute
  CrmRoute: typeof CrmRouteWithChildren
  FeedRoute: typeof FeedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistrerenRoute: typeof RegistrerenRoute
  FeedOnboardingRoute: typeof FeedOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aan-de-slag': {
      id: '/aan-de-slag'
      path: '/aan-de-slag'
      fullPath: '/aan-de-slag'
      preLoaderRoute: typeof AanDeSlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren': {
      id: '/registreren'
      path: '/registreren'
      fullPath: '/registreren'
      preLoaderRoute: typeof RegistrerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/apps': {
      id: '/crm/apps'
      path: '/apps'
      fullPath: '/crm/apps'
      preLoaderRoute: typeof CrmAppsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/campaigns': {
      id: '/crm/campaigns'
      path: '/campaigns'
      fullPath: '/crm/campaigns'
      preLoaderRoute: typeof CrmCampaignsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leadgen': {
      id: '/crm/leadgen'
      path: '/leadgen'
      fullPath: '/crm/leadgen'
      preLoaderRoute: typeof CrmLeadgenRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/messages': {
      id: '/crm/messages'
      path: '/messages'
      fullPath: '/crm/messages'
      preLoaderRoute: typeof CrmMessagesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipelines': {
      id: '/crm/pipelines'
      path: '/pipelines'
      fullPath: '/crm/pipelines'
      preLoaderRoute: typeof CrmPipelinesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/taken': {
      id: '/crm/taken'
      path: '/taken'
      fullPath: '/crm/taken'
      preLoaderRoute: typeof CrmTakenRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/webhook-signalen': {
      id: '/crm/webhook-signalen'
      path: '/webhook-signalen'
      fullPath: '/crm/webhook-signalen'
      preLoaderRoute: typeof CrmWebhookSignalenRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/workflows': {
      id: '/crm/workflows'
      path: '/workflows'
      fullPath: '/crm/workflows'
      preLoaderRoute: typeof CrmWorkflowsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/feed/': {
      id: '/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/purchased': {
      id: '/feed/purchased'
      path: '/purchased'
      fullPath: '/feed/purchased'
      preLoaderRoute: typeof FeedPurchasedRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/settings': {
      id: '/feed/settings'
      path: '/settings'
      fullPath: '/feed/settings'
      preLoaderRoute: typeof FeedSettingsRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/sold': {
      id: '/feed/sold'
      path: '/sold'
      fullPath: '/feed/sold'
      preLoaderRoute: typeof FeedSoldRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/wallet': {
      id: '/feed/wallet'
      path: '/wallet'
      fullPath: '/feed/wallet'
      preLoaderRoute: typeof FeedWalletRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed_/onboarding': {
      id: '/feed_/onboarding'
      path: '/feed/onboarding'
      fullPath: '/feed/onboarding'
      preLoaderRoute: typeof FeedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/campaigns_/$id': {
      id: '/crm/campaigns_/$id'
      path: '/campaigns/$id'
      fullPath: '/crm/campaigns/$id'
      preLoaderRoute: typeof CrmCampaignsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts_/$id': {
      id: '/crm/contacts_/$id'
      path: '/contacts/$id'
      fullPath: '/crm/contacts/$id'
      preLoaderRoute: typeof CrmContactsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts_/import': {
      id: '/crm/contacts_/import'
      path: '/contacts/import'
      fullPath: '/crm/contacts/import'
      preLoaderRoute: typeof CrmContactsImportRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/ai-agent': {
      id: '/crm/settings_/ai-agent'
      path: '/settings/ai-agent'
      fullPath: '/crm/settings/ai-agent'
      preLoaderRoute: typeof CrmSettingsAiAgentRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/custom-fields': {
      id: '/crm/settings_/custom-fields'
      path: '/settings/custom-fields'
      fullPath: '/crm/settings/custom-fields'
      preLoaderRoute: typeof CrmSettingsCustomFieldsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/eigen-whatsapp': {
      id: '/crm/settings_/eigen-whatsapp'
      path: '/settings/eigen-whatsapp'
      fullPath: '/crm/settings/eigen-whatsapp'
      preLoaderRoute: typeof CrmSettingsEigenWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/email': {
      id: '/crm/settings_/email'
      path: '/settings/email'
      fullPath: '/crm/settings/email'
      preLoaderRoute: typeof CrmSettingsEmailRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/handleiding': {
      id: '/crm/settings_/handleiding'
      path: '/settings/handleiding'
      fullPath: '/crm/settings/handleiding'
      preLoaderRoute: typeof CrmSettingsHandleidingRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/lead-flow': {
      id: '/crm/settings_/lead-flow'
      path: '/settings/lead-flow'
      fullPath: '/crm/settings/lead-flow'
      preLoaderRoute: typeof CrmSettingsLeadFlowRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/meta': {
      id: '/crm/settings_/meta'
      path: '/settings/meta'
      fullPath: '/crm/settings/meta'
      preLoaderRoute: typeof CrmSettingsMetaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/pipeline': {
      id: '/crm/settings_/pipeline'
      path: '/settings/pipeline'
      fullPath: '/crm/settings/pipeline'
      preLoaderRoute: typeof CrmSettingsPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/sms': {
      id: '/crm/settings_/sms'
      path: '/settings/sms'
      fullPath: '/crm/settings/sms'
      preLoaderRoute: typeof CrmSettingsSmsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/team': {
      id: '/crm/settings_/team'
      path: '/settings/team'
      fullPath: '/crm/settings/team'
      preLoaderRoute: typeof CrmSettingsTeamRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/templates': {
      id: '/crm/settings_/templates'
      path: '/settings/templates'
      fullPath: '/crm/settings/templates'
      preLoaderRoute: typeof CrmSettingsTemplatesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings_/whatsapp': {
      id: '/crm/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/crm/settings/whatsapp'
      preLoaderRoute: typeof CrmSettingsWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/workflows_/$id': {
      id: '/crm/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/crm/workflows/$id'
      preLoaderRoute: typeof CrmWorkflowsIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/feed/lead_/$id': {
      id: '/feed/lead_/$id'
      path: '/lead/$id'
      fullPath: '/feed/lead/$id'
      preLoaderRoute: typeof FeedLeadIdRouteImport
      parentRoute: typeof FeedRoute
    }
  }
}

interface CrmRouteChildren {
  CrmAppsRoute: typeof CrmAppsRoute
  CrmCampaignsRoute: typeof CrmCampaignsRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmLeadgenRoute: typeof CrmLeadgenRoute
  CrmMessagesRoute: typeof CrmMessagesRoute
  CrmPipelinesRoute: typeof CrmPipelinesRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
  CrmTakenRoute: typeof CrmTakenRoute
  CrmWebhookSignalenRoute: typeof CrmWebhookSignalenRoute
  CrmWorkflowsRoute: typeof CrmWorkflowsRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmCampaignsIdRoute: typeof CrmCampaignsIdRoute
  CrmContactsIdRoute: typeof CrmContactsIdRoute
  CrmContactsImportRoute: typeof CrmContactsImportRoute
  CrmSettingsAiAgentRoute: typeof CrmSettingsAiAgentRoute
  CrmSettingsCustomFieldsRoute: typeof CrmSettingsCustomFieldsRoute
  CrmSettingsEigenWhatsappRoute: typeof CrmSettingsEigenWhatsappRoute
  CrmSettingsEmailRoute: typeof CrmSettingsEmailRoute
  CrmSettingsHandleidingRoute: typeof CrmSettingsHandleidingRoute
  CrmSettingsLeadFlowRoute: typeof CrmSettingsLeadFlowRoute
  CrmSettingsMetaRoute: typeof CrmSettingsMetaRoute
  CrmSettingsPipelineRoute: typeof CrmSettingsPipelineRoute
  CrmSettingsSmsRoute: typeof CrmSettingsSmsRoute
  CrmSettingsTeamRoute: typeof CrmSettingsTeamRoute
  CrmSettingsTemplatesRoute: typeof CrmSettingsTemplatesRoute
  CrmSettingsWhatsappRoute: typeof CrmSettingsWhatsappRoute
  CrmWorkflowsIdRoute: typeof CrmWorkflowsIdRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAppsRoute: CrmAppsRoute,
  CrmCampaignsRoute: CrmCampaignsRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmLeadgenRoute: CrmLeadgenRoute,
  CrmMessagesRoute: CrmMessagesRoute,
  CrmPipelinesRoute: CrmPipelinesRoute,
  CrmSettingsRoute: CrmSettingsRoute,
  CrmTakenRoute: CrmTakenRoute,
  CrmWebhookSignalenRoute: CrmWebhookSignalenRoute,
  CrmWorkflowsRoute: CrmWorkflowsRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmCampaignsIdRoute: CrmCampaignsIdRoute,
  CrmContactsIdRoute: CrmContactsIdRoute,
  CrmContactsImportRoute: CrmContactsImportRoute,
  CrmSettingsAiAgentRoute: CrmSettingsAiAgentRoute,
  CrmSettingsCustomFieldsRoute: CrmSettingsCustomFieldsRoute,
  CrmSettingsEigenWhatsappRoute: CrmSettingsEigenWhatsappRoute,
  CrmSettingsEmailRoute: CrmSettingsEmailRoute,
  CrmSettingsHandleidingRoute: CrmSettingsHandleidingRoute,
  CrmSettingsLeadFlowRoute: CrmSettingsLeadFlowRoute,
  CrmSettingsMetaRoute: CrmSettingsMetaRoute,
  CrmSettingsPipelineRoute: CrmSettingsPipelineRoute,
  CrmSettingsSmsRoute: CrmSettingsSmsRoute,
  CrmSettingsTeamRoute: CrmSettingsTeamRoute,
  CrmSettingsTemplatesRoute: CrmSettingsTemplatesRoute,
  CrmSettingsWhatsappRoute: CrmSettingsWhatsappRoute,
  CrmWorkflowsIdRoute: CrmWorkflowsIdRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface FeedRouteChildren {
  FeedPurchasedRoute: typeof FeedPurchasedRoute
  FeedSettingsRoute: typeof FeedSettingsRoute
  FeedSoldRoute: typeof FeedSoldRoute
  FeedWalletRoute: typeof FeedWalletRoute
  FeedIndexRoute: typeof FeedIndexRoute
  FeedLeadIdRoute: typeof FeedLeadIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedPurchasedRoute: FeedPurchasedRoute,
  FeedSettingsRoute: FeedSettingsRoute,
  FeedSoldRoute: FeedSoldRoute,
  FeedWalletRoute: FeedWalletRoute,
  FeedIndexRoute: FeedIndexRoute,
  FeedLeadIdRoute: FeedLeadIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanDeSlagRoute: AanDeSlagRoute,
  CrmRoute: CrmRouteWithChildren,
  FeedRoute: FeedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistrerenRoute: RegistrerenRoute,
  FeedOnboardingRoute: FeedOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
